using Microsoft.Data.SqlClient;
using System.Data;

namespace Disconnected
{
    internal class Program
    {
        static void Main(string[] args)
        {
            string _ConStr = "Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=Dac97;Integrated Security=True";

            #region SELECT Query
            //SqlConnection con = new SqlConnection(_ConStr);

            //// This will open the connection and close the connection for us.
            //// This will fire SELECT query on database and it will get the records for us.
            //SqlDataAdapter da = new SqlDataAdapter("SELECT * FROM EMP",con);
            //// This will fetch database records along with primary key contraints to the .net side and initialization DataTable in DataSet accordingly.
            //da.MissingSchemaAction = MissingSchemaAction.AddWithKey;

            //DataSet ds= new DataSet();
            //da.Fill(ds,"Emp"); // reader the records and fill DataSet table.

            //foreach (DataRow row in ds.Tables["Emp"].Rows)
            //{
            //    int id = Convert.ToInt32(row["Id"]);
            //    string nm = row["Name"].ToString();
            //    string add = row["Address"].ToString();
            //    Console.WriteLine($"Id: {id}, Name: {nm}, Address: {add}");
            //} 
            #endregion

            #region INSERT Query
            SqlConnection con = new SqlConnection(_ConStr);
            SqlDataAdapter da = new SqlDataAdapter("SELECT * FROM EMP", con);

            da.MissingSchemaAction = MissingSchemaAction.AddWithKey;

            SqlCommandBuilder builder = new SqlCommandBuilder(da);

            DataSet ds = new DataSet();
            da.Fill(ds, "Emp");
            //ds.GetXml()

            Console.WriteLine("Enter Name:");
            string nm = Console.ReadLine();
            Console.WriteLine("Enter Address:");
            string add = Console.ReadLine();

            DataRow newRow = ds.Tables["Emp"].NewRow();
            newRow["Name"] = nm;
            newRow["Address"] = add;

            ds.Tables["Emp"].Rows.Add(newRow);

            da.Update(ds, "Emp");//Insert Query is generated by CommandBuilder
            Console.WriteLine("Record inserted!");


            #endregion

        }
    }
}
